### ISSUE TITLE
All the examples in the documentation are broken

### ISSUE THREAD

**Issue by grantbruer** [slimgroup/SlimPlotting.jl#8]
The culprit is likely this:

```
Error: MissingException: No plotting backend found, either PyPlot or Python
Plot need to be loaded in the script
```

Also, the build should probably fail if the examples fail.

**Comment by mloubout** [comment]
PythonPlot is loaded in the first cell, this is likely a Symbol/string miss-match/conversion which is needed with PythonPlot

**Comment by grantbruer** [comment]
I think it's the CondaPkg not being available through `PythonPlot.CondaPkg`.

From [here](https://github.com/slimgroup/SlimPlotting.jl/actions/runs/11561847013/job/32181754511#step:7:14)

```
[ Info: Initializing PythonPlotSlimExt
┌ Error: Error during loading of extension PythonPlotSlimExt of SlimPlotting, use `Base.retry_load_extensions()` to retry.
│   exception =
│    2-element ExceptionStack:
│    InitError: UndefVarError: `CondaPkg` not defined in `PythonPlot`
```
There may be a different package that makes it easy to access CondaPkg?

Right now, @shiqinzeng is looking into fixing this as her first foray into Julia.

**Comment by mloubout** [comment]
They must have removed itas a dependency `PythonPlot.PythonCall.CondaPkg` or `PythonPlot.PythonCall.C.CondaPkg` instead of `PythonPlot.CondaPkg` should fix it
